// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var each, stripExtension, stripFsExtensions;
  each = require('underscore').each;
  stripExtension = function (path) {
    return path.replace(/\.json$/, '');
  };
  stripFsExtensions = function (fsHash) {
    var data;
    data = {};
    each(fsHash, function (value, key) {
      return data[stripExtension(key)] = value;
    });
    return data;
  };
  module.exports = function (fsHash) {
    var data;
    data = stripFsExtensions(fsHash);
    return function (request) {
      return data[stripExtension(request.path)];
    };
  };
}.call(this);
