// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var Dsl, ResponseSpecification;
  ResponseSpecification = require('./responder').ResponseSpecification;
  Dsl = function () {
    function Dsl(param$, param$1) {
      this._addResponseSpecification = param$;
      this._path = param$1[0];
      this._withMode = 'replaceContent';
    }
    Dsl.prototype.byReplacing = function (key) {
      this._withMode = 'replaceKey';
      this._key = key;
      return this;
    };
    Dsl.prototype['with'] = function (what) {
      var spec;
      spec = function () {
        switch (this._withMode) {
        case 'replaceContent':
          return {
            path: this._path,
            method: 'GET',
            query: {},
            content: what.body,
            status: what.status
          };
        case 'replaceKey':
          return {
            path: this._path,
            method: 'GET',
            query: {},
            replaceKey: this._key,
            replaceValue: what
          };
        }
      }.call(this);
      return this._addResponseSpecification(spec);
    };
    return Dsl;
  }();
  module.exports = Dsl;
}.call(this);
