// Generated by CoffeeScript 1.10.0
var Dsl, ResponseSpecification, isObject;

isObject = require('underscore').isObject;

ResponseSpecification = require('./responder').ResponseSpecification;

Dsl = (function() {
  function Dsl(_addResponseSpecification, arg) {
    this._addResponseSpecification = _addResponseSpecification;
    this._path = arg[0];
    this._withMode = 'replaceContent';
  }

  Dsl.prototype.byReplacing = function(key) {
    this._withMode = 'replaceKey';
    this._key = key;
    return this;
  };

  Dsl.prototype["with"] = function(what) {
    var body, spec, statusCode;
    if (isObject(what)) {
      body = what.body, statusCode = what.statusCode;
    } else {
      body = what;
      statusCode = 200;
    }
    spec = (function() {
      switch (this._withMode) {
        case 'replaceContent':
          return {
            path: this._path,
            method: 'GET',
            query: {},
            body: body,
            statusCode: statusCode
          };
        case 'replaceKey':
          return {
            path: this._path,
            method: 'GET',
            query: {},
            replaceKey: this._key,
            replaceValue: what
          };
      }
    }).call(this);
    return this._addResponseSpecification(spec);
  };

  return Dsl;

})();

module.exports = Dsl;
