// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var Dsl, ResponseSpecification;
  ResponseSpecification = require('./responder').ResponseSpecification;
  Dsl = function () {
    function Dsl(param$, param$1) {
      this._addResponseSpecification = param$;
      this._path = param$1[0];
    }
    Dsl.prototype['with'] = function (what) {
      var spec;
      spec = new ResponseSpecification({
        path: this._path,
        method: 'GET',
        query: {},
        content: what
      });
      return this._addResponseSpecification(spec);
    };
    return Dsl;
  }();
  module.exports = Dsl;
}.call(this);
