// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var Dsl, express, loadJsonFiles, lumber, MockApiServer, pick, Responder;
  express = require('express');
  loadJsonFiles = require('./load_json_files');
  lumber = require('clumber');
  pick = require('underscore').pick;
  Responder = require('./responder').Responder;
  Dsl = require('./dsl');
  MockApiServer = function () {
    function MockApiServer(param$) {
      var instance$;
      instance$ = this;
      this._cannedResponses = function (a, b, c) {
        return MockApiServer.prototype._cannedResponses.apply(instance$, arguments);
      };
      this._addResponseSpecification = function (a) {
        return MockApiServer.prototype._addResponseSpecification.apply(instance$, arguments);
      };
      this.options = param$;
      this.logger = this._initLogger();
    }
    MockApiServer.prototype.start = function (done) {
      this.logger.info('[STARTING-SERVER]');
      this.app = express();
      this.app.use(this._cannedResponses);
      return loadJsonFiles('test/mock-api', function (this$) {
        return function (err, hash) {
          this$.originalResponder = this$.responder = new Responder(hash);
          return this$.server = this$.app.listen(this$.options.port, done);
        };
      }(this));
    };
    MockApiServer.prototype.stop = function () {
      this.logger.info('[STOPPING-SERVER]');
      return this.server.close();
    };
    MockApiServer.prototype.respondTo = function (args) {
      args = 1 <= arguments.length ? [].slice.call(arguments, 0) : [];
      return new Dsl(this._addResponseSpecification, args);
    };
    MockApiServer.prototype.reset = function () {
      return this.responder = this.originalResponder;
    };
    MockApiServer.prototype._addResponseSpecification = function (spec) {
      return this.responder = this.responder.withResponseSpecification(spec);
    };
    MockApiServer.prototype._initLogger = function () {
      var transports;
      transports = [];
      if (this.options.logToConsole)
        transports.push(new lumber.transports.Console);
      if (null != this.options.logToFile)
        transports.push(new lumber.transports.File({
          filename: this.options.logToFile,
          level: 'info'
        }));
      return new lumber.Logger({ transports: transports });
    };
    MockApiServer.prototype._cannedResponses = function (req, res, next) {
      var request, response;
      request = pick(req, 'method', 'path', 'query');
      this.logger.info('[MOCK-REQUEST]', request);
      response = this.responder.respondTo(request);
      if (response === void 0)
        return next();
      this.logger.info('[MOCK-RESPONSE]', response);
      res.header('Content-Type', 'application/json');
      return res.send(JSON.stringify(response));
    };
    return MockApiServer;
  }();
  module.exports = function (options, cb) {
    var server;
    server = new MockApiServer(options);
    return server.start(function (err) {
      if (!(null != cb))
        return;
      return cb(err, server);
    });
  };
}.call(this);
