// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var express, MockApiServer;
  express = require('express');
  MockApiServer = function () {
    function MockApiServer(param$) {
      this.options = param$;
    }
    MockApiServer.prototype.start = function (cb) {
      this.app = express();
      return this.server = this.app.listen(this.options.port, cb);
    };
    MockApiServer.prototype.stop = function () {
      return this.server.close();
    };
    return MockApiServer;
  }();
  module.exports = function (options, cb) {
    var server;
    server = new MockApiServer(options);
    return server.start(function (err) {
      if (!(null != cb))
        return;
      return cb(err, server);
    });
  };
}.call(this);
