// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var async, cache$, each, filter, fs, map, path, recursivelyFindFiles, safeFilenames;
  async = require('async');
  path = require('path');
  fs = require('fs');
  cache$ = require('underscore');
  each = cache$.each;
  filter = cache$.filter;
  map = cache$.map;
  safeFilenames = function (filenames) {
    return filter(filenames, function (filename) {
      return filename !== '.DS_Store';
    });
  };
  recursivelyFindFiles = function (root, resultPrefix, done) {
    return fs.readdir(root, function (err, filenames) {
      var files, fileStat;
      if (null != err)
        return done(err);
      files = map(safeFilenames(filenames), function (filename) {
        return {
          path: path.join(root, filename),
          resultPath: path.join(resultPrefix, filename)
        };
      });
      fileStat = function (file, done) {
        return fs.stat(file.path, done);
      };
      return async.map(files, fileStat, function (err, statBuffers) {
        var results, subActions;
        if (null != err)
          return done(err);
        results = [];
        subActions = [];
        each(statBuffers, function (statBuffer, i) {
          var file;
          file = files[i];
          if (statBuffer.isDirectory()) {
            return subActions.push(function (done) {
              return recursivelyFindFiles(file.path, file.resultPath, done);
            });
          } else {
            return results.push(file);
          }
        });
        return async.series(subActions, function (err, listOfSubResults) {
          if (null != err)
            return done(err);
          each(listOfSubResults, function (subResults) {
            return results = results.concat(subResults);
          });
          return done(null, results);
        });
      });
    });
  };
  module.exports = function (path, done) {
    return recursivelyFindFiles(path, '/', function (err, files) {
      var actions;
      if (null != err)
        return done(err);
      actions = {};
      each(files, function (file) {
        return actions[file.resultPath] = function (done) {
          return fs.readFile(file.path, function (err, contents) {
            if (null != err)
              return done(err);
            return done(null, JSON.parse(contents));
          });
        };
      });
      return async.parallel(actions, done);
    });
  };
}.call(this);
