// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var each, keyReplacer;
  each = require('underscore').each;
  keyReplacer = function (options) {
    return function (content) {
      eval('content.' + options.replaceKey + ' = ' + JSON.stringify(options.replaceValue));
      return content;
    };
  };
  module.exports = { keyReplacer: keyReplacer };
}.call(this);
