// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var grabAllLines, parseStatusCode;
  grabAllLines = function (fileContent) {
    return fileContent.toString('utf-8').split('\n');
  };
  parseStatusCode = function (line) {
    return line.match(/\d{3}/)[0];
  };
  module.exports = function (fileHash) {
    var body, contents, firstLine, lines, path, responseHash, secondLine, statusCode;
    responseHash = {};
    for (path in fileHash) {
      contents = fileHash[path];
      lines = grabAllLines(contents);
      firstLine = lines.shift();
      secondLine = lines.shift();
      statusCode = parseStatusCode(firstLine);
      body = JSON.parse(lines.join('\n'));
      responseHash[path] = {
        statusCode: statusCode,
        body: body
      };
    }
    return responseHash;
  };
}.call(this);
