// Generated by CoffeeScript 1.11.1
'use strict';
var grabAllLines, parseStatusCode;

grabAllLines = function(fileContent) {
  return fileContent.toString('utf-8').split('\n');
};

parseStatusCode = function(line) {
  if (line.match(/\d{3}/)) {
    return line.match(/\d{3}/)[0];
  }
};

module.exports = function(fileHash) {
  var body, contents, firstLine, lines, path, responseHash, secondLine, statusCode;
  responseHash = {};
  for (path in fileHash) {
    contents = fileHash[path];
    lines = grabAllLines(contents);
    if (lines[0].indexOf('{') === -1) {
      firstLine = lines.shift();
      secondLine = lines.shift();
      statusCode = parseStatusCode(firstLine);
    } else {
      statusCode = 200;
    }
    body = JSON.parse(lines.join('\n'));
    responseHash[path] = {
      statusCode: statusCode,
      body: body
    };
  }
  return responseHash;
};
