// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var cache$, compileNFA, each, FAIL, keys, patternMatcher, START;
  cache$ = require('underscore');
  each = cache$.each;
  keys = cache$.keys;
  FAIL = 0;
  START = 1;
  compileNFA = function (pattern) {
    var currentState, sawWildcard, states, successState;
    states = [];
    states[FAIL] = { '%': FAIL };
    currentState = START;
    sawWildcard = false;
    each(pattern, function (char) {
      if (null != states[currentState])
        states[currentState];
      else
        states[currentState] = { '%': FAIL };
      if (char === '%') {
        return states[currentState]['%'] = currentState;
      } else {
        states[currentState][char] = currentState + 1;
        currentState += 1;
        return sawWildcard = false;
      }
    });
    if (null != states[currentState])
      states[currentState];
    else
      states[currentState] = { '%': FAIL };
    successState = currentState;
    return {
      states: states,
      successState: successState
    };
  };
  module.exports = patternMatcher = function (pattern) {
    var cache$1, states, successState;
    if (!pattern)
      return false;
    cache$1 = compileNFA(pattern);
    states = cache$1.states;
    successState = cache$1.successState;
    return function (value) {
      var currentStates;
      currentStates = {};
      currentStates[START] = true;
      each(value, function (char) {
        var nextStates;
        nextStates = {};
        each(keys(currentStates), function (state) {
          nextStates[states[state]['%']] = true;
          if (null != states[state][char])
            return nextStates[states[state][char]] = true;
        });
        return currentStates = nextStates;
      });
      return null != currentStates[successState];
    };
  };
}.call(this);
