// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var Responder, responseMap;
  responseMap = require('./response_map');
  Responder = function () {
    function Responder(fileHash) {
      this.responseMap = responseMap(fileHash);
    }
    Responder.prototype.respond = function (request) {
      return this.responseMap(request);
    };
    return Responder;
  }();
  module.exports = Responder;
}.call(this);
