// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var cache$, each, extend, filter, map, patternMatcher, Responder, ResponseSpecification, size, sortBy, stripExtension, url;
  patternMatcher = require('./pattern_matcher');
  cache$ = require('underscore');
  each = cache$.each;
  extend = cache$.extend;
  filter = cache$.filter;
  map = cache$.map;
  size = cache$.size;
  sortBy = cache$.sortBy;
  url = require('url');
  stripExtension = function (path) {
    return path.replace(/\.json$/, '');
  };
  ResponseSpecification = function () {
    function ResponseSpecification(param$) {
      var cache$1;
      {
        cache$1 = param$;
        this.method = cache$1.method;
        this.path = cache$1.path;
        this.query = cache$1.query;
        this.content = cache$1.content;
        this.changeNumber = cache$1.changeNumber;
      }
      this.path = stripExtension(this.path);
      if (null != this.changeNumber)
        this.changeNumber;
      else
        this.changeNumber = 0;
    }
    ResponseSpecification.prototype.matches = function (request) {
      if (!(stripExtension(request.path) === this.path))
        return false;
      if (!(request.method === this.method))
        return false;
      return this._matchesQuery(request.query);
    };
    ResponseSpecification.prototype['with'] = function (params) {
      return new ResponseSpecification(extend({}, this, params));
    };
    ResponseSpecification.prototype._matchesQuery = function (query) {
      var matches;
      matches = true;
      each(this.query, function (value, name) {
        if (!patternMatcher(value)(query[name]))
          return matches = false;
      });
      return matches;
    };
    return ResponseSpecification;
  }();
  Responder = function () {
    function Responder(fsHash) {
      this.specs = this._buildResponseMap(fsHash);
      this.serialNumber = 0;
    }
    Responder.prototype.respondTo = function (request) {
      var allowedEntries;
      allowedEntries = filter(this.specs, function (entry) {
        return entry.matches(request);
      });
      if (allowedEntries.length === 0)
        return;
      return allowedEntries[0].content;
    };
    Responder.prototype.withResponseSpecification = function (newSpec) {
      var modifiedResponder;
      modifiedResponder = new Responder({});
      modifiedResponder.specs = this.specs.splice(0);
      modifiedResponder.specs.push(newSpec['with']({ changeNumber: this.serialNumber + 1 }));
      modifiedResponder.specs = sortBy(modifiedResponder.specs, function (spec) {
        return 1e9 - 1e3 * size(spec.query) - spec.changeNumber;
      });
      modifiedResponder.serialNumber = this.serialNumber + 1;
      return modifiedResponder;
    };
    Responder.prototype._extractMethod = function (filename) {
      var method, path;
      method = filename.split('/')[1];
      path = filename.replace(/\/[^\/]*/, '');
      return {
        method: method,
        path: path
      };
    };
    Responder.prototype._buildResponseMap = function (fsHash) {
      var specs;
      specs = map(fsHash, function (this$) {
        return function (content, filename) {
          return this$._buildStaticResponseEntry(filename, content);
        };
      }(this));
      specs = sortBy(specs, function (entry) {
        return 1e9 - size(entry.query);
      });
      return specs;
    };
    Responder.prototype._buildStaticResponseEntry = function (filename, content) {
      var cache$1, cache$2, method, path, pathname, query;
      cache$1 = url.parse(filename, true);
      pathname = cache$1.pathname;
      query = cache$1.query;
      cache$2 = this._extractMethod(stripExtension(pathname));
      method = cache$2.method;
      path = cache$2.path;
      return new ResponseSpecification({
        content: content,
        method: method,
        path: path,
        query: query
      });
    };
    return Responder;
  }();
  module.exports = {
    Responder: Responder,
    ResponseSpecification: ResponseSpecification
  };
}.call(this);
