// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var HELP_MESSAGE, mockApiServer, Server;
  mockApiServer = require('./index');
  HELP_MESSAGE = 'mock-api-server: A stand-in for a real API server\nUsage:\n\n  mock-api-server --port PORT\n\nOptions:\n\n  --port PORT           The port to listen on (required).\n';
  Server = function () {
    function Server(param$) {
      this.argv = param$;
    }
    Server.prototype.run = function () {
      var help, options;
      help = false;
      options = { logToConsole: true };
      while (this.argv.length > 0) {
        if ('--help' === this.argv[0]) {
          help = true;
          this.argv.shift();
        } else if ('--port' === this.argv[0]) {
          this.argv.shift();
          options.port = this.argv.shift() | 0;
        } else {
          console.log('Unknown option `' + this.argv[0] + '` (use --help).');
          process.exit(1);
        }
      }
      if (help) {
        console.log(HELP_MESSAGE);
        process.exit(0);
      }
      if (!options.port) {
        console.log('mock-api-server: No PORT supplied (see --help).');
        process.exit(1);
      }
      return mockApiServer(options, function (err, server) {
      });
    };
    return Server;
  }();
  module.exports = Server;
}.call(this);
